name: Publish Python Package
on:
  push:
    tags:
      - "v*" # Trigger on push of tags starting with 'v'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Set version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          # Update VERSION in setup.py
          sed -i "s/VERSION = \".*\"/VERSION = \"$VERSION\"/" setup.py
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
